[idm_primary]
idmprimarya ansible_host=192.168.1.51

[idm_replica]
idmreplicab ansible_host=192.168.1.52

[idm_servers:children]
idm_primary
idm_replica

[idm_loadbalancers]
idmloadbalancer1 ansible_host=192.168.1.53
idmloadbalancer2 ansible_host=192.168.1.54

[idm_clients]
idmclient1a ansible_host=192.168.1.61
idmclient2a ansible_host=192.168.1.62
idmclient1b ansible_host=192.168.1.63
idmclient2b ansible_host=192.168.1.64

[idm_admin]
idmadmin ansible_host=127.0.0.1 ansible_connection=local

[idm_all:children]
idm_servers
idm_loadbalancers
idm_clients
idm_admin

[idm_all:vars]
ansible_user=iriven
ansible_become=true
ansible_become_method=sudo
