worker_processes auto;

events { worker_connections 1024; }

stream {
  upstream ldap_backend {
    server idmprimarya:389 max_fails=3 fail_timeout=10s;
    server idmreplicab:389 backup;
  }
  upstream ldaps_backend {
    server idmprimarya:636 max_fails=3 fail_timeout=10s;
    server idmreplicab:636 backup;
  }
  server { listen 389; proxy_pass ldap_backend; proxy_timeout 10s; proxy_connect_timeout 3s; }
  server { listen 636; proxy_pass ldaps_backend; proxy_timeout 10s; proxy_connect_timeout 3s; }
}

http {
  upstream idm_http_backend {
    server idmprimarya:80 max_fails=3 fail_timeout=10s;
    server idmreplicab:80 backup;
  }
  upstream idm_https_backend {
    server idmprimarya:443 max_fails=3 fail_timeout=10s;
    server idmreplicab:443 backup;
  }

  server { listen 80; location / { proxy_pass http://idm_http_backend; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; } }
  server { listen 443 ssl; ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem; ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key; location / { proxy_pass https://idm_https_backend; proxy_ssl_verify off; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; } }
}
