---
idm_rbac_user_groups:
  - name: linux-admins
    desc: "Senior Linux infrastructure administrators"

  - name: devops-admins
    desc: "Application platform administrators"

  - name: security-auditors
    desc: "Read-only security and compliance auditors"

  - name: db-admins
    desc: "Database administrators"

  - name: idm-admins
    desc: "FreeIPA platform administrators"

  - name: breakglass-admins
    desc: "Emergency administrators with global privileged access"

idm_rbac_hostgroups:
  - name: linux-all
    desc: "All Linux systems"

  - name: idm-servers
    desc: "FreeIPA primary and replica servers"

  - name: app-servers
    desc: "Application servers"

  - name: db-servers
    desc: "Database servers"

  - name: jump-hosts
    desc: "Bastion and administration hosts"