#!/usr/bin/env bash
set -euo pipefail

cat > /etc/idm-lab.env <<EOF
DOMAIN=${DOMAIN}
REALM=${REALM}
IPA_SERVER_HOSTNAME=${IPA_SERVER_HOSTNAME}
IPA_SERVER_SHORTNAME=${IPA_SERVER_SHORTNAME:-ipa}
IPA_SERVER_IP=${IPA_SERVER_IP}
IPA_ADMIN_PASSWORD=${IPA_ADMIN_PASSWORD}
IPA_DM_PASSWORD=${IPA_DM_PASSWORD}
DNS_FORWARDER=${DNS_FORWARDER}
IPA_CLIENT_1_HOSTNAME=${IPA_CLIENT_1_HOSTNAME:-}
IPA_CLIENT_1_IP=${IPA_CLIENT_1_IP:-}
IPA_CLIENT_2_HOSTNAME=${IPA_CLIENT_2_HOSTNAME:-}
IPA_CLIENT_2_IP=${IPA_CLIENT_2_IP:-}
SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
EOF

chmod 0600 /etc/idm-lab.env
exec /usr/sbin/init
