---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ idm_domain }}"

- name: Configure hosts file for IPA servers
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^(?!#).*\s{{ item.fqdn | regex_escape() }}(\s|$)'
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.hostname }}"
    owner: root
    group: root
    mode: "0644"
    create: true
    state: present
  when:
    - item.ip is defined
    - item.fqdn is defined
    - item.hostname is defined
  with_items:
    - { ip: '{{ idm_primary_ip }}', fqdn: '{{ idm_primary_fqdn }}', hostname: '{{ idm_primary_hostname }}' }
    - { ip: '{{ idm_replica_ip }}', fqdn: '{{ idm_replica_fqdn }}', hostname: '{{ idm_replica_hostname }}' }
    - { ip: '{{ idm_lb_vip }}', fqdn: '{{ idm_lb_vip_fqdn }}', hostname: '{{ idm_lb_vip_fqdn.split(".")|first|lower }}' }

- name: Install base packages
  ansible.builtin.dnf:
    name:
      - vim
      - curl
      - wget
      - bind-utils
      - chrony
      - firewalld
      - nmap-ncat
      - rsync
      - python3
      - sudo
    state: present

- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Set SELinux permissive runtime
  ansible.builtin.command: setenforce 0
  changed_when: false
  failed_when: false

- name: Set SELinux permissive persistently
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=permissive'
