---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ idm_domain }}"

- name: Maintain IDM hosts entries
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED IDM LAB HOSTS"
    block: |
      {{ idm_primary_ip }} {{ idm_primary_fqdn }} {{ idm_primary_hostname }}
      {{ idm_replica_ip }} {{ idm_replica_fqdn }} {{ idm_replica_hostname }}
      {{ idm_lb_vip }} {{ idm_lb_vip_fqdn }} idmloadbalancer
    owner: root
    group: root
    mode: "0644"

- name: Install base packages
  ansible.builtin.dnf:
    name:
      - vim
      - curl
      - wget
      - bind-utils
      - chrony
      - firewalld
      - python3
      - sudo
    state: present

- name: Enable mandatories services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - sshd
    - chronyd
    - firewalld

- name: Set SELinux permissive runtime
  ansible.builtin.command: setenforce 0
  changed_when: false
  failed_when: false

- name: Set SELinux permissive persistently
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=permissive'

