---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ idm_domain }}"

- name: Maintain IDM hosts entries
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED IDM LAB HOSTS"
    block: |
      {{ idm_primary_ip }} {{ idm_primary_fqdn }} {{ idm_primary_hostname }}
      {{ idm_replica_ip }} {{ idm_replica_fqdn }} {{ idm_replica_hostname }}
      {{ idm_lb_vip }} {{ idm_lb_vip_fqdn }} idmloadbalancer
