name: ${COMPOSE_PROJECT_NAME}

x-ipa-common: &ipa-common
  image: freeipa/freeipa-server:rocky-9
  privileged: true
  cgroup: host
  cgroup_parent: docker.slice
  security_opt:
    - seccomp=unconfined
  sysctls:
    net.ipv6.conf.all.disable_ipv6: "0"
    net.ipv6.conf.lo.disable_ipv6: "0"
  tmpfs:
    - /run
    - /tmp
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:rw
  restart: "no"

x-idm-extra-hosts: &idm-extra-hosts
  - "${IDM_PRIMARY_FQDN} ${IDM_PRIMARY_HOST}:${IDM_PRIMARY_IP}"
  - "${IDM_REPLICA_FQDN} ${IDM_REPLICA_HOST}:${IDM_REPLICA_IP}"
  - "${IDM_LOADBALANCER_FQDN} ${IDM_LOADBALANCER_HOST}:${IDM_LOADBALANCER_A_IP}"
  - "${IDMCLIENT1A_FQDN} ${IDMCLIENT1A_HOST}:${IDMCLIENT1A_IP}"
  - "${IDMCLIENT2A_FQDN} ${IDMCLIENT2A_HOST}:${IDMCLIENT2A_IP}"
  - "${IDMCLIENT1B_FQDN} ${IDMCLIENT1B_HOST}:${IDMCLIENT1B_IP}"
  - "${IDMCLIENT2B_FQDN} ${IDMCLIENT2B_HOST}:${IDMCLIENT2B_IP}"
  - "${IDMNODE1A_FQDN} ${IDMNODE1A_HOST}:${IDMNODE1A_IP}"
  - "${IDMNODE1B_FQDN} ${IDMNODE1B_HOST}:${IDMNODE1B_IP}"

services:
  idmprimarya:
    <<: *ipa-common
    container_name: ${IDM_PRIMARY_HOST}
    hostname: "${IDM_PRIMARY_FQDN}"
    tty: true
    stdin_open: true
    stop_signal: SIGRTMIN+3 
    extra_hosts: *idm-extra-hosts
    volumes:
      - idmprimarya_data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      site_a:
        ipv4_address: ${IDM_PRIMARY_IP}
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "1080:80/tcp"
      - "1443:443/tcp"
      - "1088:88/tcp"
      - "1088:88/udp"
      - "1464:464/tcp"
      - "1464:464/udp"
      - "1389:389/tcp"
      - "1636:636/tcp"
    command:
      - ipa-server-install
      - -U
      - -r
      - ${REALM}
      - -n
      - ${DOMAIN}
      - -p
      - ${IPA_DM_PASSWORD}
      - -a
      - ${IPA_ADMIN_PASSWORD}
      - --hostname
      - ${IDM_PRIMARY_FQDN}
      - --ip-address
      - ${IDM_PRIMARY_IP}
      # - --setup-dns
      # - --forwarder=${DNS_FORWARDER_1}
      # - --forwarder=${DNS_FORWARDER_2}
      # - --forward-policy=${DNS_FORWARD_POLICY}
      # - --no-reverse
      # - --allow-zone-overlap
      - --no-ntp
      - --no-ssh
      - --no-sshd
      - --no-dns-sshfp
      - --skip-mem-check

  idmreplicab:
    <<: *ipa-common
    container_name: ${IDM_REPLICA_HOST}
    hostname: ${IDM_REPLICA_FQDN}
    tty: true
    stdin_open: true
    stop_signal: SIGRTMIN+3     
    extra_hosts: *idm-extra-hosts
    volumes:
      - idmreplicab_data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      site_b:
        ipv4_address: ${IDM_REPLICA_IP}
    ports:
      - "2053:53/tcp"
      - "2053:53/udp"
      - "2080:80/tcp"
      - "2443:443/tcp"
      - "2088:88/tcp"
      - "2088:88/udp"
      - "2464:464/tcp"
      - "2464:464/udp"
      - "2389:389/tcp"
      - "2636:636/tcp"
    command:
      - no-exit

  idmloadbalancer:
    image: nginx:stable
    container_name: ${IDM_LOADBALANCER_HOST}
    hostname: ${IDM_LOADBALANCER_FQDN}
    depends_on:
      - idmprimarya
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts: *idm-extra-hosts
    networks:
      site_a:
        ipv4_address: ${IDM_LOADBALANCER_A_IP}
      site_b:
        ipv4_address: ${IDM_LOADBALANCER_B_IP}
    ports:
      - "8080:80/tcp"
      - "8443:443/tcp"
      - "1388:389/tcp"
      - "1637:636/tcp"

  idmclient1a: &client_a_base
    build: ./client
    container_name: ${IDMCLIENT1A_HOST}
    hostname: ${IDMCLIENT1A_FQDN}
    dns:
      - ${IDM_PRIMARY_IP}
    extra_hosts: *idm-extra-hosts
    environment:
      SSH_ROOT_PASSWORD: ${SSH_ROOT_PASSWORD}
    networks:
      site_a:
        ipv4_address: ${IDMCLIENT1A_IP}

  idmclient2a:
    <<: *client_a_base
    container_name: ${IDMCLIENT2A_HOST}
    hostname: ${IDMCLIENT2A_FQDN}
    networks:
      site_a:
        ipv4_address: ${IDMCLIENT2A_IP}

  idmnode1a:
    <<: *client_a_base
    container_name: ${IDMNODE1A_HOST}
    hostname: ${IDMNODE1A_FQDN}
    networks:
      site_a:
        ipv4_address: ${IDMNODE1A_IP}

  idmclient1b: &client_b_base
    build: ./client
    container_name: ${IDMCLIENT1B_HOST}
    hostname: ${IDMCLIENT1B_FQDN}
    dns:
      - ${IDM_PRIMARY_IP}
      - ${IDM_REPLICA_IP}
    extra_hosts: *idm-extra-hosts
    environment:
      SSH_ROOT_PASSWORD: ${SSH_ROOT_PASSWORD}
    networks:
      site_b:
        ipv4_address: ${IDMCLIENT1B_IP}

  idmclient2b:
    <<: *client_b_base
    container_name: ${IDMCLIENT2B_HOST}
    hostname: ${IDMCLIENT2B_FQDN}
    networks:
      site_b:
        ipv4_address: ${IDMCLIENT2B_IP}

  idmnode1b:
    <<: *client_b_base
    container_name: ${IDMNODE1B_HOST}
    hostname: ${IDMNODE1B_FQDN}
    networks:
      site_b:
        ipv4_address: ${IDMNODE1B_IP}

networks:
  site_a:
    driver: bridge
    ipam:
      config:
        - subnet: ${SITE_A_SUBNET}
          gateway: ${SITE_A_GATEWAY}
  site_b:
    driver: bridge
    ipam:
      config:
        - subnet: ${SITE_B_SUBNET}
          gateway: ${SITE_B_GATEWAY}

volumes:
  idmprimarya_data:
  idmreplicab_data:
