---
idm_monitoring_log_dir: /var/log/idm-monitoring
idm_monitoring_scripts_dir: /usr/local/libexec/idm-monitoring
idm_monitoring_timer_on_calendar: "*-*-* *:00/15:00"
idm_monitoring_disk_warning_percent: 80
idm_monitoring_disk_critical_percent: 90
idm_monitoring_enable_ipa_healthcheck: true
idm_monitoring_enable_replication_check: true
idm_monitoring_enable_cert_check: true
idm_monitoring_enable_chrony_check: true
idm_monitoring_enable_haproxy_check: true
idm_monitoring_enable_disk_check: true
