services:
  ipa-server:
    build:
      context: ./server
    container_name: ipa-server
    hostname: ${IPA_SERVER_HOSTNAME}
    privileged: true
    env_file:
      - .env
    networks:
      idm_net:
        ipv4_address: ${IPA_SERVER_IP}
    ports:
      - "2220:22"
      - "389:389"
      - "636:636"
      - "88:88"
      - "88:88/udp"
      - "464:464"
      - "464:464/udp"
    volumes:
      - ipa_data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    stop_signal: SIGRTMIN+3
  ipa-nginx:
    build:
      context: ./nginx
    container_name: ${IPA_NGINX_SHORTNAME}
    depends_on:
      - ipa-server
    networks:
      idm_net:
        ipv4_address: ${IPA_NGINX_IP}
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  ipa-client1:
    build:
      context: ./client
    container_name: ipa-client1
    hostname: ${IPA_CLIENT_1_HOSTNAME}
    privileged: true
    env_file:
      - .env
    networks:
      idm_net:
        ipv4_address: ${IPA_CLIENT_1_IP}
    dns:
      - ${IPA_SERVER_IP}
    ports:
      - "2221:22"
    depends_on:
      - ipa-server
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    stop_signal: SIGRTMIN+3

  ipa-client2:
    build:
      context: ./client
    container_name: ipa-client2
    hostname: ${IPA_CLIENT_2_HOSTNAME}
    privileged: true
    env_file:
      - .env
    networks:
      idm_net:
        ipv4_address: ${IPA_CLIENT_2_IP}
    dns:
      - ${IPA_SERVER_IP}
    ports:
      - "2222:22"
    depends_on:
      - ipa-server
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    stop_signal: SIGRTMIN+3

networks:
  idm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.192/26

volumes:
  ipa_data:


