---
- name: Install FreeIPA replica
  hosts: idm_replica
  become: true

  roles:
    - common_hosts
    - chrony_server
    - ipa_replica
    - pki_baseline
    - ssh_hardening
    - audit_baseline
    - ipa_monitoring_baseline
