---
- name: Enroll clients into FreeIPA
  hosts: idm_clients:idm_admin
  become: true

  roles:
    - common_hosts
    - chrony_client
    - ipa_client
    - ssh_hardening
    - audit_baseline
    - log_rotation
    - ipa_monitoring_baseline
