---
- name: Validate secrets baseline
  import_playbook: 88-validate-secrets.yml

- name: Bootstrap common configuration
  import_playbook: 00-bootstrap-common.yml

- name: Configure Chrony on IDM servers
  import_playbook: 05-configure-chrony-servers.yml

- name: Install FreeIPA primary
  import_playbook: 10-install-primary.yml

- name: Install FreeIPA replica
  import_playbook: 20-install-replica.yml

- name: Configure DNS and NTP records
  import_playbook: 25-configure-dns-ntp-records.yml

- name: Configure load balancers
  import_playbook: 40-configure-loadbalancers.yml

- name: Configure Chrony on clients and admin hosts
  import_playbook: 06-configure-chrony-clients.yml

- name: Enroll clients and administration host
  import_playbook: 30-enroll-clients.yml

- name: Configure RBAC, HBAC and sudo policies
  import_playbook: 50-configure-rbac.yml

- name: Configure FreeIPA backup automation
  import_playbook: 70-configure-backup.yml

- name: Configure log rotation
  import_playbook: 87-configure-log-rotation.yml

- name: Validate backup restore readiness
  import_playbook: 71-test-backup-restore-readiness.yml

- name: Run platform healthcheck
  import_playbook: 60-healthcheck.yml

- name: Validate platform
  import_playbook: 90-validate-platform.yml

- name: Run HA failover checks
  import_playbook: 92-ha-failover-check.yml

- name: Run Disaster Recovery readiness check
  import_playbook: 95-dr-readiness-check.yml

- name: Run patch baseline checks
  import_playbook: 94-patch-baseline-check.yml

- name: Run platform compliance check
  import_playbook: 96-compliance-check.yml
