---
- name: Validate IPA service status on servers
  ansible.builtin.command: ipactl status
  register: ipactl_status
  changed_when: false
  when: inventory_hostname in groups['idm_servers']

- name: Validate Chrony status
  ansible.builtin.command: chronyc sources
  register: chronyc_sources
  changed_when: false

- name: Validate SSSD status on clients
  ansible.builtin.command: sssctl domain-status {{ idm_domain }}
  register: sssd_status
  changed_when: false
  failed_when: false
  when: inventory_hostname in (groups['idm_clients'] + groups['idm_admin'])

- name: Validate HAProxy stats endpoint on load balancers
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ idm_lb_stats_port }}/stats"
    return_content: false
    status_code: 200
  when: inventory_hostname in groups['idm_loadbalancers']
